version: '3'

services:
  db:
    container_name: postgress-db
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=todos2022
      - POSTGRES_DB=todoapp
    networks:
      - api-networks
  # run pgadmin just for development
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - 5050:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: psql@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   networks:
  #     - api-networks
  #   depends_on:
  #     - db
  api:
    container_name: express-todos-api-postgress
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - api-networks
    depends_on:
      - db

volumes:
  database-data:
  # pgadmin-data:
networks:
  api-networks:
    driver: bridge
